import "package:dart_web_test/solid.dart";
import "package:web/web.dart" as web;

import "../solid_dom/core/listbox.dart";
import "../solid_dom/core/listbox_core.dart";

/// Styled Listbox handle factory (Solidus UI skin).
///
/// For an unstyled primitive, use `createListboxCore` from `solid_dom`.
ListboxHandle<T, O> createListbox<T, O extends ListboxItem<T>>({
  required String id,
  List<O> Function()? options,
  Iterable<ListboxSection<T, O>> Function()? sections,
  required T? Function() selected,
  required void Function(O option, int index) onSelect,
  void Function()? onClearSelection,
  bool Function(T a, T b)? equals,
  Signal<int>? activeIndex,
  int Function()? initialActiveIndex,
  bool shouldUseVirtualFocus = false,
  bool tabFocusable = false,
  bool shouldFocusOnHover = true,
  bool shouldFocusWrap = true,
  bool disallowTypeAhead = false,
  bool enableKeyboardNavigation = true,
  bool selectOnFocus = false,
  bool shouldSelectOnPressUp = false,
  bool allowsDifferentPressOrigin = false,
  bool disallowEmptySelection = false,
  void Function()? onTabOut,
  void Function()? onEscape,
  String emptyText = "No results.",
  bool showEmptyState = false,
  Object? Function(O option)? getOptionKey,
  ListboxIdRegistry<T, O>? idRegistry,
  web.HTMLElement? Function()? scrollContainer,
  bool useInnerScrollContainer = false,
  void Function(int index)? scrollToIndex,
  int Function()? pageSize,
  ListboxOptionBuilder<T, O>? optionBuilder,
  ListboxOptionBuilderReactive<T, O>? optionBuilderReactive,
}) {
  return createListboxCore(
    id: id,
    options: options,
    sections: sections,
    selected: selected,
    onSelect: onSelect,
    onClearSelection: onClearSelection,
    equals: equals,
    activeIndex: activeIndex,
    initialActiveIndex: initialActiveIndex,
    shouldUseVirtualFocus: shouldUseVirtualFocus,
    tabFocusable: tabFocusable,
    shouldFocusOnHover: shouldFocusOnHover,
    shouldFocusWrap: shouldFocusWrap,
    disallowTypeAhead: disallowTypeAhead,
    enableKeyboardNavigation: enableKeyboardNavigation,
    selectOnFocus: selectOnFocus,
    shouldSelectOnPressUp: shouldSelectOnPressUp,
    allowsDifferentPressOrigin: allowsDifferentPressOrigin,
    disallowEmptySelection: disallowEmptySelection,
    onTabOut: onTabOut,
    onEscape: onEscape,
    emptyText: emptyText,
    showEmptyState: showEmptyState,
    getOptionKey: getOptionKey,
    idRegistry: idRegistry,
    scrollContainer: scrollContainer,
    useInnerScrollContainer: useInnerScrollContainer,
    rootClassName: "card listbox",
    scrollClassName: "listboxScroll",
    optionClassName: "listboxOption",
    sectionGroupClassName: "listboxGroup",
    sectionLabelClassName: "listboxGroupLabel",
    emptyClassName: "listboxEmpty",
    scrollToIndex: scrollToIndex,
    pageSize: pageSize,
    optionBuilder: optionBuilder,
    optionBuilderReactive: optionBuilderReactive,
  );
}

